version: '3.8'

services:
  # PostgreSQL Database for production
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ai_prompt_manager
      POSTGRES_USER: prompt_user
      POSTGRES_PASSWORD: secure_password_change_me
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - prompt_network
    restart: unless-stopped

  # Redis Cache for production
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - prompt_network
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

  # AI Prompt Manager Application with Modern Web UI (Production)
  app:
    # Use latest stable release from GitHub Container Registry
    image: ghcr.io/makercorn/ai-prompt-manager:stable
    ports:
      - "7860:7860"  # Modern Web UI (FastAPI + HTMX)
      - "7861:7861"  # API Server
    environment:
      # Application Mode (unified launcher configuration)
      MULTITENANT_MODE: ${MULTITENANT_MODE:-true}   # Enable multi-tenant mode with authentication
      ENABLE_API: ${ENABLE_API:-true}               # Enable API endpoints
      USE_GRADIO: ${USE_GRADIO:-false}              # Use modern web UI (default)
      
      # Database Configuration (PostgreSQL for production)
      DB_TYPE: postgres
      POSTGRES_DSN: postgresql://prompt_user:secure_password_change_me@postgres:5432/ai_prompt_manager
      
      # Server Configuration
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: "7860"
      DEBUG: ${DEBUG:-false}
      
      # Authentication & Security (Production settings)
      SECRET_KEY: ${SECRET_KEY:-your-production-secret-key-change-this}
      LOCAL_DEV_MODE: "false"
      
      # Python Path for new architecture
      PYTHONPATH: "/app/src:/app"
      
      # SSO Configuration (configure as needed)
      SSO_ENABLED: ${SSO_ENABLED:-false}
      ADFS_ENABLED: ${ADFS_ENABLED:-false}
      SSO_CLIENT_ID: ${SSO_CLIENT_ID:-}
      SSO_CLIENT_SECRET: ${SSO_CLIENT_SECRET:-}
      SSO_AUTHORITY: ${SSO_AUTHORITY:-}
      SSO_REDIRECT_URI: ${SSO_REDIRECT_URI:-http://localhost:7860/auth/callback}
      
      # LangWatch Optimization (optional)
      LANGWATCH_API_KEY: ${LANGWATCH_API_KEY:-}
      LANGWATCH_PROJECT_ID: ${LANGWATCH_PROJECT_ID:-ai-prompt-manager}
      
      # New Architecture Configuration
      ENABLE_NEW_ARCHITECTURE: ${ENABLE_NEW_ARCHITECTURE:-true}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      
      # Redis Configuration (for caching and performance)
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
    
    volumes:
      - app_data:/app/data
    depends_on:
      - postgres
      - redis
    networks:
      - prompt_network
    restart: unless-stopped
    
    # Health check (updated for modern web UI)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/login", "||", "curl", "-f", "http://localhost:7860/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
  app_data:
  redis_data:

networks:
  prompt_network:
    driver: bridge