version: '3.8'

services:
  # PostgreSQL Database (optional, for production)
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ai_prompt_manager
      POSTGRES_USER: prompt_user
      POSTGRES_PASSWORD: secure_password_change_me
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - prompt_network

  # AI Prompt Manager Application with API
  app:
    # Use pre-built image from GitHub Container Registry
    image: ghcr.io/OWNER/REPO:latest
    # Or build locally by uncommenting the line below and commenting the image line
    # build: .
    ports:
      - "7860:7860"  # Web UI and API endpoints
    environment:
      # Database Configuration (uncomment for PostgreSQL)
      # DB_TYPE: postgres
      # POSTGRES_DSN: postgresql://prompt_user:secure_password_change_me@postgres:5432/ai_prompt_manager
      
      # SQLite Configuration (default)
      DB_TYPE: sqlite
      DB_PATH: /app/data/prompts.db
      
      # Authentication & Security
      SECRET_KEY: change-this-secret-key-in-production
      LOCAL_DEV_MODE: "false"  # Set to false for production
      
      # SSO Configuration (configure if needed)
      SSO_ENABLED: "false"
      ADFS_ENABLED: "false"
      # SSO_CLIENT_ID: your-client-id
      # SSO_CLIENT_SECRET: your-client-secret
      # SSO_AUTHORITY: https://login.microsoftonline.com/your-tenant
      # SSO_REDIRECT_URI: http://localhost:7860/auth/callback
      
      # Application
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: "7860"
    
    volumes:
      - app_data:/app/data
    depends_on:
      - postgres
    networks:
      - prompt_network

volumes:
  postgres_data:
  app_data:

networks:
  prompt_network:
    driver: bridge