services:
  # PostgreSQL Database (optional, for production)
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ai_prompt_manager
      POSTGRES_USER: prompt_user
      POSTGRES_PASSWORD: secure_password_change_me
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - prompt_network

  # Redis Cache (optional, for enhanced performance)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - prompt_network
    command: redis-server --appendonly yes

  # AI Prompt Manager Application with FastAPI Web UI
  app:
    # Use pre-built image from GitHub Container Registry
    image: ghcr.io/makercorn/ai-prompt-manager:latest
    # Or build locally by uncommenting the line below and commenting the image line
    # build: .
    ports:
      - "7860:7860"  # FastAPI Web UI (Primary Interface)
      - "7861:7861"  # FastAPI API Server (Dual-Server Architecture)
    environment:
      # Application Mode (unified launcher configuration)
      MULTITENANT_MODE: "true"   # Enable multi-tenant mode with authentication
      ENABLE_API: "true"         # Enable dual-server API architecture
      
      # Database Configuration (uncomment for PostgreSQL)
      # DB_TYPE: postgres
      # POSTGRES_DSN: postgresql://prompt_user:secure_password_change_me@postgres:5432/ai_prompt_manager
      
      # SQLite Configuration (default)
      DB_TYPE: sqlite
      DB_PATH: /app/data/prompts.db
      
      # Server Configuration
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: "7860"
      
      # Authentication & Security
      SECRET_KEY: change-this-secret-key-in-production
      LOCAL_DEV_MODE: "false"  # Set to false for production
      
      # Python Path for hybrid architecture (legacy + new)
      PYTHONPATH: "/app/src:/app"
      
      # AI Services Configuration
      PROMPT_OPTIMIZER: "builtin"   # Use built-in optimizer (no external API required)
      TRANSLATION_SERVICE: "mock"   # Use mock translator for demo purposes
      
      # SSO Configuration (configure if needed)
      SSO_ENABLED: "false"
      ADFS_ENABLED: "false"
      # SSO_CLIENT_ID: your-client-id
      # SSO_CLIENT_SECRET: your-client-secret
      # SSO_AUTHORITY: https://login.microsoftonline.com/your-tenant
      # SSO_REDIRECT_URI: http://localhost:7860/auth/callback
      
      # LangWatch Optimization (optional)
      # LANGWATCH_API_KEY: your-langwatch-api-key
      # LANGWATCH_PROJECT_ID: ai-prompt-manager
      
      # Redis Configuration (optional, for caching)
      # REDIS_URL: redis://redis:6379/0
    
    volumes:
      - app_data:/app/data
    depends_on:
      - postgres
      - redis
    networks:
      - prompt_network

volumes:
  postgres_data:
  app_data:
  redis_data:

networks:
  prompt_network:
    driver: bridge